"""Update tag

Revision ID: 1dae51f22bb2
Revises: afe80fda900d
Create Date: 2024-01-08 23:40:12.994407

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dae51f22bb2"
down_revision: Union[str, None] = "afe80fda900d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("create_time", sa.DateTime(), nullable=True))
    op.add_column("tag", sa.Column("update_time", sa.DateTime(), nullable=True))
    op.execute("UPDATE tag SET create_time = datetime('now'), update_time = datetime('now')")
    op.create_index(op.f("ix_tag_name"), "tag", ["name"], unique=True)
    with op.batch_alter_table("tag") as batch_op:
        batch_op.alter_column("create_time", nullable=False)
        batch_op.alter_column("update_time", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tag_name"), table_name="tag")
    op.drop_column("tag", "update_time")
    op.drop_column("tag", "create_time")
    # ### end Alembic commands ###
