"""Initial migration

Revision ID: 2402cd81dacf
Revises:
Create Date: 2024-01-07 21:16:56.287628

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2402cd81dacf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("food") as batch_op:
        batch_op.alter_column("images", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("update_time", existing_type=sa.DATETIME(), nullable=False)
        batch_op.create_foreign_key("fk_food_parent", "food", ["parent_id"], ["id"])

    with op.batch_alter_table("weigh") as batch_op:
        batch_op.alter_column("update_time", existing_type=sa.DATETIME(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weigh") as batch_op:
        batch_op.alter_column("update_time", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("food") as batch_op:
        batch_op.drop_constraint("fk_food_parent", type_="foreignkey")
        batch_op.alter_column("update_time", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("images", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
